# Generated by Django 4.1.2 on 2022-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_holder',
            name='date',
            field=models.DateField(default='2020-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_holder',
            name='priority',
            field=models.IntegerField(default='22'),
            preserve_default=False,
        ),
    ]
